# **Basic Demo** 

In [ ]:
print('Lecture 3')

Lecture 3


Numeric variable types

In [ ]:
x = 2
y = 3.0
z = 4.0 + 5.0j

print(x)
print(y)
print(z)

2
3.0
(4+5j)


Strings

In [ ]:
"Strings can be " + "combined"

'Strings can be combined'

In [ ]:
"Repeat! " * 3

'Repeat! Repeat! Repeat! '

Lists

In [ ]:
my_list= [3, "egg", 6.2, 7]
print(my_list[0], my_list[1], my_list[-1])

3 egg 7


# **Basic Control Structures**

If-Else

In [ ]:
a = 400 
b= a
if a is b:
  print("a and b are the same")

a and b are the same


In [ ]:
x= 0
if x == 0:
  print("x is zero")
elif x < 0:
  print("x is negative")
elif x > 1000: 
  print("x is large")
else:
  print("x is something completely different")

x is zero


While Loop

In [ ]:
x=0

while x < 10:
  print('Loop', x+1) 
  x+= 1

Loop 1
Loop 2
Loop 3
Loop 4
Loop 5
Loop 6
Loop 7
Loop 8
Loop 9
Loop 10


For Loop

In [ ]:
cars = ['Audi', 'BMW', 'Porsche', 'Merc']
for car in cars: 
  print("Car is ", car)

Car is  Audi
Car is  BMW
Car is  Porsche
Car is  Merc


## Functions

In [ ]:
def square(x):
  return x ** 2

def multiply(a, b):
  return a * b

# Functions can be composed.
square(multiply(3, 2))

36

To improve code readability, it is sometimes useful to explicitly name the arguments

# NumPy

NumPy is a popular library for storing arrays of numbers and performing computations on them. Not only this enables to write often more succint code, this also makes the code faster, since most NumPy routines are implemented in C for speed.

To use NumPy in your program, you need to import it as follows

In [ ]:
import numpy as np

## Array creation



NumPy arrays can be created from Python lists

In [ ]:
my_array = np.array([1, 2, 3])
my_array

array([1, 2, 3])

NumPy supports array of arbitrary dimension. For example, we can create two-dimensional arrays (e.g. to store a matrix) as follows

In [ ]:
my_2d_array = np.array([[1, 2, 3], [4, 5, 6]])
my_2d_array

array([[1, 2, 3],
       [4, 5, 6]])

We can access individual elements of a 2d-array using two indices

In [ ]:
my_2d_array[1, 2]

6

We can also access rows

In [ ]:
my_2d_array[1]

array([4, 5, 6])

and columns

In [ ]:
my_2d_array[:, 2]

array([3, 6])

Arrays have a `shape` attribute

In [ ]:
print(my_array.shape)
print(my_2d_array.shape)

(3,)
(2, 3)


Contrary to Python lists, NumPy arrays must have a type and all elements of the array must have the same type.

In [ ]:
my_array.dtype

dtype('int64')

The main types are `int32` (32-bit integers), `int64` (64-bit integers), `float32` (32-bit real values) and `float64` (64-bit real values).

The `dtype` can be specified when creating the array

In [ ]:
my_array = np.array([1, 2, 3], dtype=np.float64)
my_array.dtype

dtype('float64')

We can create arrays of all zeros using

In [ ]:
zero_array = np.zeros((2, 3))
zero_array

array([[0., 0., 0.],
       [0., 0., 0.]])

and similarly for all ones using `ones` instead of `zeros`.

We can create a range of values using

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

or specifying the starting point

In [ ]:
np.arange(3, 5)

array([3, 4])

Another useful routine is `linspace` for creating linearly spaced values in an interval. For instance, to create 10 values in `[0, 1]`, we can use

In [ ]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

Another important operation is `reshape`, for changing the shape of an array

In [ ]:
my_array = np.array([1, 2, 3, 4, 5, 6])
my_array.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

Play with these operations and make sure you understand them well.

## Basic operations

In NumPy, we express computations directly over arrays. This makes the code much more succint.

Arithmetic operations can be performed directly over arrays. For instance, assuming two arrays have a compatible shape, we can add them as follows

In [ ]:
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
array_a + array_b

array([5, 7, 9])

Compare this with the equivalent computation using a for loop

In [ ]:
array_out = np.zeros_like(array_a)
for i in range(len(array_a)):
  array_out[i] = array_a[i] + array_b[i]
array_out

array([5, 7, 9])

Not only this code is more verbose, it will also run much more slowly.

In NumPy, functions that operates on arrays in an element-wise fashion are called [universal functions](https://numpy.org/doc/stable/reference/ufuncs.html). For instance, this is the case of `np.sin`

In [ ]:
np.sin(array_a)

array([0.84147098, 0.90929743, 0.14112001])

Vector inner product can be performed using `np.dot`

In [ ]:
np.dot(array_a, array_b)

32

When the two arguments to `np.dot` are both 2d arrays, `np.dot` becomes matrix multiplication

In [ ]:
array_A = np.random.rand(5, 3)
array_B = np.random.randn(3, 4)
np.dot(array_A, array_B)

array([[-0.36045702, -0.81071381, -0.19270751,  1.68942764],
       [-1.37444349, -3.05245084, -0.52466652, -0.02343348],
       [-1.43277431, -2.95828896, -0.4035378 , -0.50852563],
       [-0.8569399 , -0.99003545,  0.17051909,  1.02933425],
       [-0.47198448, -1.52564526, -0.41890404, -1.29330023]])

Matrix transpose can be done using `.transpose()` or `.T` for short

In [ ]:
array_A.T

array([[0.83246658, 0.86545167, 0.62386601, 0.473339  , 0.06991272],
       [0.02185012, 0.93435538, 0.93170156, 0.0036374 , 0.7230155 ],
       [0.08128956, 0.83778882, 0.96709345, 0.66291745, 0.2734715 ]])

## Slicing and masking

Like Python lists, NumPy arrays support slicing

In [ ]:
np.arange(10)[5:]

array([5, 6, 7, 8, 9])

We can also select only certain elements from the array

In [ ]:
x = np.arange(10)
mask = x >= 5
x[mask]

array([5, 6, 7, 8, 9])